# Generated by Django 4.2.4 on 2023-12-28 01:38

import Shift.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_alter_user_off_day1_alter_user_off_day2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('MANNING_POST', 'Manning Post')], max_length=12)),
                ('first_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_guard_shifts', to='User.user')),
                ('second_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_guard_shifts', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='GuardRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('end_date', models.DateField(default=Shift.models.default_end_date, unique=True)),
                ('a_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_shift_rounds', to='Shift.shift')),
                ('b_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_shift_rounds', to='Shift.shift')),
                ('manning_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manning_post_rounds', to='Shift.shift')),
            ],
        ),
    ]
