# Generated by Django 4.2.4 on 2023-12-27 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField(help_text='Format: dd-mm-yyyy', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?972\\d{8,10}$', message='Israeli phone number must be in the format +972XXXXXXXXX')])),
                ('commander_contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?972\\d{8,10}$', message='Israeli phone number must be in the format +972XXXXXXXXX')])),
                ('off_day1', models.CharField(blank=True, help_text='Format: dd-mm-yyyy', max_length=10)),
                ('off_day2', models.CharField(blank=True, help_text='Format: dd-mm-yyyy', max_length=10)),
                ('off_weekend', models.BooleanField(default=False, help_text='Format: dd-mm-yyyy')),
                ('password', models.CharField(default='', max_length=10)),
                ('month_frequency', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('b_objection', models.BooleanField(default=False)),
                ('lieutenant', models.BooleanField(default=False)),
            ],
        ),
    ]
