# Generated by Django 4.2.4 on 2023-12-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(help_text='Format: dd-mm-yyyy', null=True),
        ),
    ]
