# Generated by Django 4.2.6 on 2023-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_day1',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_day2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_weekend',
            field=models.DateField(blank=True),
        ),
    ]
