# Generated by Django 4.2.6 on 2023-12-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_birth_date_alter_user_off_day1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='off_day1',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_day2',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_weekend',
            field=models.DateField(blank=True, default=None),
        ),
    ]
