# Generated by Django 4.2.6 on 2023-12-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_off_day1_alter_user_off_day2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='off_day1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_day2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='off_weekend',
            field=models.DateField(blank=True, null=True),
        ),
    ]
